name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Load nvm
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Use Node.js v22.13.1
            nvm use v22.13.1

            # Debugging: Print Node.js and npm versions
            echo "Node.js version: $(node -v)"
            echo "npm version: $(npm -v)"

            # Navigate to the app directory
            cd apps/Portfolio/

            # Pull the latest changes from GitHub
            git pull origin main

            # Install dependencies
            npm install

            # Build the app
            npm run build

            # Restart the PM2 process
            pm2 restart next-portfolio
